### ISSUE TITLE
Error while creating DataConnectionChecker

### ISSUE THREAD

**Issue by aaongr** [lastra-dev/clean-architecture-tdd-course#2]
Hello,
A wonderful and amazing new day and week for all of Us :)

Run all tests - passed - OK

When I try to run it I get

```
Error while creating DataConnectionChecker
Stack trace:
 dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49                                    throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 413:5                                                 new
packages/data_connection_checker_tv/data_connection_checker.dart 61:7                                           get DEFAULT_ADDRESSES
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 835:8                                 get
packages/data_connection_checker_tv/data_connection_checker.dart 89:41                                          __
packages/data_connection_checker_tv/data_connection_checker.dart 109:72                                         get _instance
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 835:8                                 get
packages/data_connection_checker_tv/data_connection_checker.dart 93:38                                          new
packages/clean_architecture_tdd_course/injection_container.dart 59:34                                           <fn>

```

**Comment by lastradev** [comment]
Hello and amazing day to you too!
It seems to me that you are trying to run the app on the web, unfortunately the data_connection_checker_tv package is not compatible with the web platform as the documentation says.

![image](https://user-images.githubusercontent.com/56526315/142910836-9f384c9d-c880-45e3-833a-d58f37a1bda6.png)
https://pub.dev/packages/data_connection_checker_tv

You can try to remove the package from the project or change it to another one that meets a similar solution if you want to run it on the web, although I'm not sure if any other package will give you a problem.

Otherwise the app works fine on Android (I haven't tested it on iOS or desktop systems).

Thanks for the issue, please let me know if you spot another problem, have a good one! :wave:

**Comment by aaongr** [comment]
Great!
Thank you
With my warmest regards for all of Us :)
